/**
 * Heartbeat Report System
 *
 * Reports are generated by BullMQ jobs on schedule:
 * - Daily: 5 AM - tactical focus for today
 * - Weekly: Monday 6 AM - operational performance
 * - Monthly: 1st of month 7 AM - strategic patterns
 * - Quarterly: Q start 8 AM - executive overview
 *
 * Each report contains raw metrics + AI-generated insights.
 */

import { z } from "zod";

// ─────────────────────────────────────────────────────────────
// COMMON METRICS
// ─────────────────────────────────────────────────────────────

export const CXMetricsSchema = z.object({
  // Volume
  totalTickets: z.number(),
  newTickets: z.number(),
  resolvedTickets: z.number(),
  openTickets: z.number(),

  // Response & Resolution
  avgResponseTimeMinutes: z.number(),
  avgResolutionTimeHours: z.number(),
  medianResponseTimeMinutes: z.number(),
  medianResolutionTimeHours: z.number(),

  // CSAT
  avgCsatScore: z.number(), // 1-10 scale
  csatResponseCount: z.number(),
  csatByScore: z.record(z.number()), // { "10": 15, "9": 12, ... }

  // Breakdown
  ticketsByStatus: z.record(z.number()), // { "open": 10, "resolved": 50 }
  ticketsByPriority: z.record(z.number()), // { "urgent": 5, "high": 10 }
  ticketsByCategory: z.record(z.number()), // AI-categorized
  ticketsByTag: z.record(z.number()),

  // Trends (compared to previous period)
  ticketCountChange: z.number(), // percentage
  responseTimeChange: z.number(),
  csatChange: z.number(),
});

export type CXMetrics = z.infer<typeof CXMetricsSchema>;

export const TeamMemberMetricsSchema = z.object({
  memberId: z.string(),
  memberName: z.string(),

  ticketsHandled: z.number(),
  ticketsResolved: z.number(),
  avgResponseTimeMinutes: z.number(),
  avgResolutionTimeHours: z.number(),
  avgCsatScore: z.number().optional(),
  csatCount: z.number(),

  // Ranking within team
  rank: z.number().optional(),
  rankChange: z.number().optional(), // vs previous period
});

export type TeamMemberMetrics = z.infer<typeof TeamMemberMetricsSchema>;

// ─────────────────────────────────────────────────────────────
// FOCUS ITEMS (80/20)
// ─────────────────────────────────────────────────────────────

export const FocusItemSchema = z.object({
  id: z.string().uuid(),

  // What it is
  title: z.string(),
  description: z.string(),
  category: z.enum([
    "bug",
    "feature_request",
    "documentation",
    "process",
    "training",
    "other",
  ]),

  // Impact scoring
  impactScore: z.number(), // 0-100
  effortEstimate: z.enum(["quick", "medium", "large"]),
  impactEffortRatio: z.number(), // Higher = better ROI

  // Evidence
  relatedTicketCount: z.number(),
  affectedCustomerCount: z.number(),
  affectedMrr: z.number().optional(), // Revenue at risk
  exampleTicketIds: z.array(z.string()),

  // Recommendation
  suggestedAssignee: z
    .object({
      id: z.string(),
      name: z.string(),
      reason: z.string(), // "Owns billing code", "Fixed similar issue before"
    })
    .optional(),

  suggestedAction: z.string(), // "Fix the billing sync bug"
  estimatedImpact: z.string(), // "Resolves ~40% of open tickets"
});

export type FocusItem = z.infer<typeof FocusItemSchema>;

// ─────────────────────────────────────────────────────────────
// AI INSIGHTS
// ─────────────────────────────────────────────────────────────

export const InsightSchema = z.object({
  id: z.string().uuid(),
  type: z.enum([
    "positive_driver", // What's going well
    "negative_driver", // What's hurting CX
    "pattern", // Recurring theme
    "anomaly", // Unusual spike/drop
    "recommendation", // Suggested action
    "team_highlight", // Team member recognition
    "risk_signal", // Churn risk, escalation, etc.
  ]),

  title: z.string(),
  description: z.string(),
  severity: z.enum(["info", "warning", "critical"]).optional(),

  // Supporting data
  evidence: z.array(z.string()), // Bullet points of supporting facts
  relatedTicketIds: z.array(z.string()).optional(),
  relatedCustomerIds: z.array(z.string()).optional(),
  relatedMemberIds: z.array(z.string()).optional(),

  // Actionability
  suggestedAction: z.string().optional(),
  actionPriority: z.enum(["low", "medium", "high"]).optional(),
});

export type Insight = z.infer<typeof InsightSchema>;

// ─────────────────────────────────────────────────────────────
// REPORT TYPES
// ─────────────────────────────────────────────────────────────

// Base report structure
const BaseReportSchema = z.object({
  id: z.string().uuid(),
  type: z.enum(["daily", "weekly", "monthly", "quarterly"]),
  periodStart: z.date(),
  periodEnd: z.date(),
  generatedAt: z.date(),

  // Raw metrics
  metrics: CXMetricsSchema,

  // Team breakdown
  teamMetrics: z.array(TeamMemberMetricsSchema),

  // AI-generated content
  summary: z.string(), // 2-3 sentence executive summary
  insights: z.array(InsightSchema),
});

// ─────────────────────────────────────────────────────────────
// DAILY REPORT
// ─────────────────────────────────────────────────────────────

export const DailyReportSchema = BaseReportSchema.extend({
  type: z.literal("daily"),

  // Today's focus (80/20 items)
  focusItems: z.array(FocusItemSchema).max(5),

  // Overnight activity
  overnightTickets: z.number(),
  overnightAlerts: z.array(
    z.object({
      type: z.string(),
      message: z.string(),
      severity: z.enum(["info", "warning", "critical"]),
      timestamp: z.date(),
    })
  ),

  // Personal queue (for the viewing user)
  personalQueue: z
    .array(
      z.object({
        ticketId: z.string(),
        subject: z.string(),
        priority: z.string(),
        impactScore: z.number(),
        waitingHours: z.number(),
      })
    )
    .optional(),

  // Yesterday's outcomes
  yesterdayResolved: z.number(),
  yesterdayWins: z.array(z.string()), // Quick highlights
});

export type DailyReport = z.infer<typeof DailyReportSchema>;

// ─────────────────────────────────────────────────────────────
// WEEKLY REPORT
// ─────────────────────────────────────────────────────────────

export const WeeklyReportSchema = BaseReportSchema.extend({
  type: z.literal("weekly"),

  // CX score with context
  cxScore: z.object({
    score: z.number(), // 1-10
    trend: z.enum(["up", "down", "stable"]),
    changePercent: z.number(),
    benchmarkComparison: z.string().optional(), // "Above industry average"
  }),

  // What drove CX
  positiveDrivers: z.array(z.string()),
  negativeDrivers: z.array(z.string()),

  // Team leaderboard
  topPerformers: z.array(
    z.object({
      memberId: z.string(),
      memberName: z.string(),
      highlight: z.string(), // "Fastest response time"
      stats: z.string(), // "94% CSAT, 12min avg response"
    })
  ),

  needsAttention: z.array(
    z.object({
      memberId: z.string(),
      memberName: z.string(),
      concern: z.string(), // "CSAT dropped 15%"
      suggestion: z.string(), // "May benefit from coaching on..."
    })
  ),

  // Issue clusters (recurring themes)
  issueClusters: z.array(
    z.object({
      name: z.string(),
      ticketCount: z.number(),
      trend: z.enum(["increasing", "decreasing", "stable"]),
      suggestedFix: z.string().optional(),
    })
  ),

  // 80/20 for next week
  nextWeekFocus: z.array(FocusItemSchema).max(3),
});

export type WeeklyReport = z.infer<typeof WeeklyReportSchema>;

// ─────────────────────────────────────────────────────────────
// MONTHLY REPORT
// ─────────────────────────────────────────────────────────────

export const MonthlyReportSchema = BaseReportSchema.extend({
  type: z.literal("monthly"),

  // Trend over 4 weeks
  weeklyTrend: z.array(
    z.object({
      weekStart: z.date(),
      cxScore: z.number(),
      ticketCount: z.number(),
      avgResponseTime: z.number(),
    })
  ),

  // Systemic issues (need product/engineering)
  systemicIssues: z.array(
    z.object({
      title: z.string(),
      description: z.string(),
      recurringWeeks: z.number(),
      totalTickets: z.number(),
      estimatedFixEffort: z.enum(["small", "medium", "large"]),
      suggestedOwner: z.string().optional(), // "Product team", "Engineering"
    })
  ),

  // Team development
  teamDevelopment: z.array(
    z.object({
      memberId: z.string(),
      memberName: z.string(),
      trend: z.enum(["improving", "stable", "declining"]),
      strengths: z.array(z.string()),
      growthAreas: z.array(z.string()),
      suggestedTraining: z.array(z.string()).optional(),
    })
  ),

  // Customer segments
  segmentBreakdown: z.array(
    z.object({
      segment: z.string(), // "Enterprise", "Pro", "Free"
      ticketCount: z.number(),
      avgCsat: z.number(),
      topIssues: z.array(z.string()),
    })
  ),

  // Churn risk
  churnRiskCustomers: z.array(
    z.object({
      customerId: z.string(),
      customerName: z.string(),
      mrr: z.number().optional(),
      riskSignals: z.array(z.string()),
      suggestedAction: z.string(),
    })
  ),

  // Product feedback digest
  productFeedback: z.array(
    z.object({
      category: z.enum(["feature_request", "bug", "ux_issue", "other"]),
      summary: z.string(),
      mentionCount: z.number(),
      customerSegments: z.array(z.string()),
    })
  ),

  // Efficiency metrics
  efficiency: z.object({
    ticketsPerAgent: z.number(),
    costPerTicket: z.number().optional(),
    automationRate: z.number().optional(), // % handled by bots
    firstContactResolutionRate: z.number(),
  }),

  // Recommendations
  recommendations: z.array(
    z.object({
      title: z.string(),
      description: z.string(),
      type: z.enum(["hire", "train", "process", "tooling", "documentation"]),
      estimatedImpact: z.string(),
      effort: z.enum(["low", "medium", "high"]),
    })
  ),
});

export type MonthlyReport = z.infer<typeof MonthlyReportSchema>;

// ─────────────────────────────────────────────────────────────
// QUARTERLY REPORT
// ─────────────────────────────────────────────────────────────

export const QuarterlyReportSchema = BaseReportSchema.extend({
  type: z.literal("quarterly"),

  // Executive summary (3 bullets max)
  executiveSummary: z.array(z.string()).max(3),

  // Quarter over quarter comparison
  quarterComparison: z.object({
    currentQuarter: z.string(), // "Q1 2025"
    previousQuarter: z.string(),
    cxScoreChange: z.number(),
    volumeChange: z.number(),
    efficiencyChange: z.number(),
    highlights: z.array(z.string()),
    concerns: z.array(z.string()),
  }),

  // Monthly trend
  monthlyTrend: z.array(
    z.object({
      month: z.string(),
      cxScore: z.number(),
      ticketCount: z.number(),
      teamSize: z.number(),
      ticketsPerAgent: z.number(),
    })
  ),

  // Customer retention impact
  retentionImpact: z.object({
    churnedCustomers: z.number(),
    churnedMrr: z.number(),
    cxCorrelation: z.string(), // "Customers with CSAT <6 churned 3x more"
    savedCustomers: z.number().optional(), // Saved through CX intervention
    savedMrr: z.number().optional(),
  }),

  // ROI analysis
  roiAnalysis: z.object({
    supportCost: z.number(),
    revenueProtected: z.number().optional(),
    costPerTicket: z.number(),
    costPerResolution: z.number(),
    automationSavings: z.number().optional(),
  }),

  // Team scaling
  teamScaling: z.object({
    currentSize: z.number(),
    ticketsPerAgent: z.number(),
    burnoutRisk: z.enum(["low", "medium", "high"]),
    recommendation: z.enum(["hire", "maintain", "optimize"]),
    suggestedHeadcount: z.number().optional(),
    reasoning: z.string(),
  }),

  // Big bets (strategic recommendations)
  strategicRecommendations: z.array(
    z.object({
      title: z.string(),
      description: z.string(),
      investmentLevel: z.enum(["small", "medium", "large"]),
      expectedImpact: z.string(),
      timeframe: z.string(), // "Next quarter", "6 months"
      dependencies: z.array(z.string()).optional(),
    })
  ),

  // Suggested OKRs
  suggestedOkrs: z.array(
    z.object({
      objective: z.string(),
      keyResults: z.array(
        z.object({
          metric: z.string(),
          target: z.string(),
          current: z.string(),
        })
      ),
    })
  ),
});

export type QuarterlyReport = z.infer<typeof QuarterlyReportSchema>;

// ─────────────────────────────────────────────────────────────
// UNION TYPE
// ─────────────────────────────────────────────────────────────

export type Report = DailyReport | WeeklyReport | MonthlyReport | QuarterlyReport;

// ─────────────────────────────────────────────────────────────
// REPORT GENERATION CONFIG
// ─────────────────────────────────────────────────────────────

export const ReportConfigSchema = z.object({
  // Scheduling
  timezone: z.string().default("UTC"),
  dailyTime: z.string().default("05:00"), // 5 AM
  weeklyDay: z.number().default(1), // Monday
  weeklyTime: z.string().default("06:00"),
  monthlyDay: z.number().default(1), // 1st of month
  monthlyTime: z.string().default("07:00"),
  quarterlyTime: z.string().default("08:00"),

  // Delivery
  deliveryChannels: z.array(z.enum(["dashboard", "email", "slack"])),
  emailRecipients: z.array(z.string()).optional(),
  slackChannel: z.string().optional(),

  // Customization
  includeTeamMetrics: z.boolean().default(true),
  includeIndividualMetrics: z.boolean().default(true),
  anonymizeTeamMembers: z.boolean().default(false), // For privacy
  focusItemCount: z.number().default(3),

  // AI settings
  aiProvider: z.enum(["openai", "anthropic", "ollama"]),
  insightDepth: z.enum(["brief", "standard", "detailed"]).default("standard"),
});

export type ReportConfig = z.infer<typeof ReportConfigSchema>;
