/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WallboardTrendsRouteImport } from './routes/wallboard/trends'
import { Route as WallboardPulseRouteImport } from './routes/wallboard/pulse'
import { Route as WallboardLiveRouteImport } from './routes/wallboard/live'
import { Route as WallboardAttentionRouteImport } from './routes/wallboard/attention'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallboardTrendsRoute = WallboardTrendsRouteImport.update({
  id: '/wallboard/trends',
  path: '/wallboard/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const WallboardPulseRoute = WallboardPulseRouteImport.update({
  id: '/wallboard/pulse',
  path: '/wallboard/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const WallboardLiveRoute = WallboardLiveRouteImport.update({
  id: '/wallboard/live',
  path: '/wallboard/live',
  getParentRoute: () => rootRouteImport,
} as any)
const WallboardAttentionRoute = WallboardAttentionRouteImport.update({
  id: '/wallboard/attention',
  path: '/wallboard/attention',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/wallboard/attention': typeof WallboardAttentionRoute
  '/wallboard/live': typeof WallboardLiveRoute
  '/wallboard/pulse': typeof WallboardPulseRoute
  '/wallboard/trends': typeof WallboardTrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/wallboard/attention': typeof WallboardAttentionRoute
  '/wallboard/live': typeof WallboardLiveRoute
  '/wallboard/pulse': typeof WallboardPulseRoute
  '/wallboard/trends': typeof WallboardTrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/wallboard/attention': typeof WallboardAttentionRoute
  '/wallboard/live': typeof WallboardLiveRoute
  '/wallboard/pulse': typeof WallboardPulseRoute
  '/wallboard/trends': typeof WallboardTrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/wallboard/attention'
    | '/wallboard/live'
    | '/wallboard/pulse'
    | '/wallboard/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/wallboard/attention'
    | '/wallboard/live'
    | '/wallboard/pulse'
    | '/wallboard/trends'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/wallboard/attention'
    | '/wallboard/live'
    | '/wallboard/pulse'
    | '/wallboard/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  WallboardAttentionRoute: typeof WallboardAttentionRoute
  WallboardLiveRoute: typeof WallboardLiveRoute
  WallboardPulseRoute: typeof WallboardPulseRoute
  WallboardTrendsRoute: typeof WallboardTrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallboard/trends': {
      id: '/wallboard/trends'
      path: '/wallboard/trends'
      fullPath: '/wallboard/trends'
      preLoaderRoute: typeof WallboardTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallboard/pulse': {
      id: '/wallboard/pulse'
      path: '/wallboard/pulse'
      fullPath: '/wallboard/pulse'
      preLoaderRoute: typeof WallboardPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallboard/live': {
      id: '/wallboard/live'
      path: '/wallboard/live'
      fullPath: '/wallboard/live'
      preLoaderRoute: typeof WallboardLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallboard/attention': {
      id: '/wallboard/attention'
      path: '/wallboard/attention'
      fullPath: '/wallboard/attention'
      preLoaderRoute: typeof WallboardAttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  WallboardAttentionRoute: WallboardAttentionRoute,
  WallboardLiveRoute: WallboardLiveRoute,
  WallboardPulseRoute: WallboardPulseRoute,
  WallboardTrendsRoute: WallboardTrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
